### ISSUE TITLE
Push notification systems

### ISSUE THREAD

**Issue by puria** [ForkbombEu/wallet#6]
State of the art with capacitor the best solution will be something hosted on-premise

**Comment by phoebus-84** [comment]
The easiest thing would be to use this capacitor extension and integrate it with firebase as reported here: https://capacitorjs.com/docs/apis/push-notifications
Alternatively there are a lot of services we could use instead of firebase for push notifications: probably oneSignal, https://onesignal.com/ ,  is enought good and offer free subscription plans (other services, like airship, are very expensive).
But if we want to host our own service we can use something like Gotify: https://github.com/gotify
It is widely adopted, still in maintenance and written in go. 
Pigeon, https://github.com/codedge-llc/pigeon ,  is a valid alternative in elixir.
Other projects I saw are discontinued or abandoned, but maybe can be used as a template like https://github.com/uniqush/uniqush-push .
